export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  TENANT_ADMIN: 'TENANT_ADMIN',
  STORE_MANAGER: 'STORE_MANAGER',
  WAREHOUSE_MANAGER: 'WAREHOUSE_MANAGER',
  CASHIER: 'CASHIER',
  WAREHOUSE_OP: 'WAREHOUSE_OP',
  VIEWER: 'VIEWER',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_HIERARCHY: Record<Role, number> = {
  SUPER_ADMIN: 100,
  TENANT_ADMIN: 80,
  STORE_MANAGER: 60,
  WAREHOUSE_MANAGER: 60,
  CASHIER: 40,
  WAREHOUSE_OP: 40,
  VIEWER: 20,
};

export const ADMIN_ROLES: Role[] = ['SUPER_ADMIN', 'TENANT_ADMIN'];
export const MANAGER_ROLES: Role[] = [...ADMIN_ROLES, 'STORE_MANAGER', 'WAREHOUSE_MANAGER'];
export const OPERATOR_ROLES: Role[] = [...MANAGER_ROLES, 'CASHIER', 'WAREHOUSE_OP'];
